// All PDF tools data
export interface Tool {
  id: string;
  title: string;
  description: string;
  href: string;
  category: "organize" | "optimize" | "convert" | "edit" | "security" | "intelligence";
  color: string;
  bgColor: string;
  iconColor: string;
}

export const tools: Tool[] = [
  // Organize
  {
    id: "merge_pdf",
    title: "Merge PDF",
    description: "Combine PDFs in the order you want with the easiest PDF merger available.",
    href: "/merge_pdf",
    category: "organize",
    color: "#EE6C4D",
    bgColor: "#FEF0EC",
    iconColor: "#EE6C4D",
  },
  {
    id: "split_pdf",
    title: "Split PDF",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    href: "/split_pdf",
    category: "organize",
    color: "#EE6C4D",
    bgColor: "#FEF0EC",
    iconColor: "#EE6C4D",
  },
  {
    id: "remove_pages",
    title: "Remove pages",
    description: "Remove one or multiple pages from a PDF document.",
    href: "/remove-pages",
    category: "organize",
    color: "#EE6C4D",
    bgColor: "#FEF0EC",
    iconColor: "#EE6C4D",
  },
  {
    id: "extract_pages",
    title: "Extract pages",
    description: "Select and extract pages from your PDF to create a new file.",
    href: "/extract-pages",
    category: "organize",
    color: "#EE6C4D",
    bgColor: "#FEF0EC",
    iconColor: "#EE6C4D",
  },
  {
    id: "organize_pdf",
    title: "Organize PDF",
    description: "Sort, add and delete PDF pages. Also rotate and move pages.",
    href: "/organize-pdf",
    category: "organize",
    color: "#EE6C4D",
    bgColor: "#FEF0EC",
    iconColor: "#EE6C4D",
  },
  {
    id: "scan_pdf",
    title: "Scan to PDF",
    description: "Capture document as PDF directly from your mobile camera.",
    href: "/scan-pdf",
    category: "organize",
    color: "#EE6C4D",
    bgColor: "#FEF0EC",
    iconColor: "#EE6C4D",
  },

  // Optimize
  {
    id: "compress_pdf",
    title: "Compress PDF",
    description: "Reduce file size while optimizing for maximal PDF quality.",
    href: "/compress_pdf",
    category: "optimize",
    color: "#8FBC5D",
    bgColor: "#F0F8E8",
    iconColor: "#8FBC5D",
  },
  {
    id: "repair_pdf",
    title: "Repair PDF",
    description: "Repair a damaged PDF and recover data from corrupt PDF.",
    href: "/repair-pdf",
    category: "optimize",
    color: "#8FBC5D",
    bgColor: "#F0F8E8",
    iconColor: "#8FBC5D",
  },
  {
    id: "ocr_pdf",
    title: "OCR PDF",
    description: "Easily convert scanned PDF to searchable and selectable text.",
    href: "/ocr-pdf",
    category: "optimize",
    color: "#8FBC5D",
    bgColor: "#F0F8E8",
    iconColor: "#8FBC5D",
  },

  // Convert to PDF
  {
    id: "jpg_to_pdf",
    title: "JPG to PDF",
    description: "Convert JPG, PNG, BMP, GIF, and TIFF images to PDF.",
    href: "/jpg_to_pdf",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "word_to_pdf",
    title: "Word to PDF",
    description: "Make DOC and DOCX files easy to read by converting them to PDF.",
    href: "/word_to_pdf",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "powerpoint_to_pdf",
    title: "PowerPoint to PDF",
    description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
    href: "/powerpoint_to_pdf",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "excel_to_pdf",
    title: "Excel to PDF",
    description: "Make EXCEL spreadsheets easy to read by converting them to PDF.",
    href: "/excel_to_pdf",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "html_to_pdf",
    title: "HTML to PDF",
    description: "Convert webpages in HTML to PDF. Copy and paste the URL.",
    href: "/html-to-pdf",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "pdf_to_jpg",
    title: "PDF to JPG",
    description: "Convert each PDF page into a JPG or extract all images from a PDF.",
    href: "/pdf_to_jpg",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "pdf_to_word",
    title: "PDF to Word",
    description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.",
    href: "/pdf_to_word",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "pdf_to_powerpoint",
    title: "PDF to PowerPoint",
    description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
    href: "/pdf_to_powerpoint",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "pdf_to_excel",
    title: "PDF to Excel",
    description: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
    href: "/pdf_to_excel",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },
  {
    id: "pdf_to_pdfa",
    title: "PDF to PDF/A",
    description: "Transform your PDF to PDF/A, the ISO-standardized version for long-term archiving.",
    href: "/pdf_to_pdfa",
    category: "convert",
    color: "#5F83C6",
    bgColor: "#EBF1FD",
    iconColor: "#5F83C6",
  },

  // Edit
  {
    id: "rotate_pdf",
    title: "Rotate PDF",
    description: "Rotate your PDFs the way you need them. Even rotate multiple PDFs at once!",
    href: "/rotate_pdf",
    category: "edit",
    color: "#ab6993",
    bgColor: "#F5EDF5",
    iconColor: "#ab6993",
  },
  {
    id: "add_page_numbers",
    title: "Add page numbers",
    description: "Add page numbers into PDFs with ease. Choose your positions, dimensions and typography!",
    href: "/add_pdf_page_number",
    category: "edit",
    color: "#ab6993",
    bgColor: "#F5EDF5",
    iconColor: "#ab6993",
  },
  {
    id: "add_watermark",
    title: "Add watermark",
    description: "Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.",
    href: "/pdf_add_watermark",
    category: "edit",
    color: "#ab6993",
    bgColor: "#F5EDF5",
    iconColor: "#ab6993",
  },
  {
    id: "crop_pdf",
    title: "Crop PDF",
    description: "Crop PDF pages. Trim PDF margins easily with custom cropping settings.",
    href: "/crop-pdf",
    category: "edit",
    color: "#ab6993",
    bgColor: "#F5EDF5",
    iconColor: "#ab6993",
  },
  {
    id: "edit_pdf",
    title: "Edit PDF",
    description: "Add text, images, shapes or freehand annotations to a PDF document.",
    href: "/edit-pdf",
    category: "edit",
    color: "#ab6993",
    bgColor: "#F5EDF5",
    iconColor: "#ab6993",
  },
  {
    id: "pdf_forms",
    title: "PDF Forms",
    description: "Create, fill and edit PDF forms. Import or export form data easily.",
    href: "/pdf-forms",
    category: "edit",
    color: "#ab6993",
    bgColor: "#F5EDF5",
    iconColor: "#ab6993",
  },

  // Security
  {
    id: "unlock_pdf",
    title: "Unlock PDF",
    description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    href: "/unlock_pdf",
    category: "security",
    color: "#F4A261",
    bgColor: "#FEF4EC",
    iconColor: "#F4A261",
  },
  {
    id: "protect_pdf",
    title: "Protect PDF",
    description: "Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.",
    href: "/protect-pdf",
    category: "security",
    color: "#F4A261",
    bgColor: "#FEF4EC",
    iconColor: "#F4A261",
  },
  {
    id: "sign_pdf",
    title: "Sign PDF",
    description: "Sign yourself or request electronic signatures from others.",
    href: "/sign-pdf",
    category: "security",
    color: "#F4A261",
    bgColor: "#FEF4EC",
    iconColor: "#F4A261",
  },
  {
    id: "redact_pdf",
    title: "Redact PDF",
    description: "Redact content by removing and erasing sensitive information from your PDF.",
    href: "/redact-pdf",
    category: "security",
    color: "#F4A261",
    bgColor: "#FEF4EC",
    iconColor: "#F4A261",
  },
  {
    id: "compare_pdf",
    title: "Compare PDF",
    description: "Show a word-by-word comparison of two PDF documents.",
    href: "/compare-pdf",
    category: "security",
    color: "#F4A261",
    bgColor: "#FEF4EC",
    iconColor: "#F4A261",
  },

  // Intelligence
  {
    id: "ai_summarizer",
    title: "AI Summarizer",
    description: "Get an AI-powered summary of any PDF document in seconds.",
    href: "/pdf-summarize",
    category: "intelligence",
    color: "#6C63FF",
    bgColor: "#F0EEFF",
    iconColor: "#6C63FF",
  },
  {
    id: "translate_pdf",
    title: "Translate PDF",
    description: "Instantly translate PDF documents into other languages.",
    href: "/translate-pdf",
    category: "intelligence",
    color: "#6C63FF",
    bgColor: "#F0EEFF",
    iconColor: "#6C63FF",
  },
];

export const categories = [
  { id: "all", label: "All" },
  { id: "organize", label: "Organize PDF" },
  { id: "optimize", label: "Optimize PDF" },
  { id: "convert", label: "Convert PDF" },
  { id: "edit", label: "Edit PDF" },
  { id: "security", label: "PDF Security" },
  { id: "intelligence", label: "PDF Intelligence" },
];
